"""Unit and integration tests for Streamlit frontend components and API client."""

import os
import sys
from pathlib import Path
import pytest
from unittest.mock import patch, MagicMock

# Ensure capstone root is on sys.path
CAPSTONE_ROOT = Path(__file__).resolve().parent.parent
if str(CAPSTONE_ROOT) not in sys.path:
    sys.path.insert(0, str(CAPSTONE_ROOT))

from frontend.api_client import (
    get_backend_url,
    check_health,
    predict_churn,
    DEFAULT_BACKEND_URL,
)


@pytest.fixture
def sample_payload_19_features():
    """Exact 19-feature payload generated by Streamlit form."""
    return {
        "gender": "Female",
        "SeniorCitizen": 0,
        "Partner": "No",
        "Dependents": "No",
        "tenure": 3,
        "PhoneService": "Yes",
        "MultipleLines": "No",
        "InternetService": "Fiber optic",
        "OnlineSecurity": "No",
        "OnlineBackup": "No",
        "DeviceProtection": "No",
        "TechSupport": "No",
        "StreamingTV": "Yes",
        "StreamingMovies": "No",
        "Contract": "Month-to-month",
        "PaperlessBilling": "Yes",
        "PaymentMethod": "Electronic check",
        "MonthlyCharges": 79.85,
        "TotalCharges": 239.55,
    }


def test_api_client_import():
    """1 & 2. Verify api_client imports and exposes core functions."""
    import frontend.api_client as client
    assert hasattr(client, "get_backend_url")
    assert hasattr(client, "check_health")
    assert hasattr(client, "predict_churn")


def test_backend_url_configuration():
    """3. Verify backend URL retrieval with default and env override."""
    # Test default
    if "BACKEND_URL" in os.environ:
        del os.environ["BACKEND_URL"]
    assert get_backend_url() == DEFAULT_BACKEND_URL

    # Test override
    os.environ["BACKEND_URL"] = "http://custom-host:9000/"
    assert get_backend_url() == "http://custom-host:9000"
    del os.environ["BACKEND_URL"]


def test_check_health_success():
    """4. Test check_health parses successful 200 response."""
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "status": "healthy",
        "model_loaded": True,
        "model_name": "LightGBM Classifier Pipeline",
        "version": "1.0.0",
    }

    with patch("requests.get", return_value=mock_resp):
        res = check_health("http://dummy-host:8000")
        assert res["is_available"] is True
        assert res["status"] == "healthy"
        assert res["model_loaded"] is True
        assert res["model_name"] == "LightGBM Classifier Pipeline"


def test_check_health_connection_failure():
    """7. Test check_health handles connection error gracefully."""
    import requests
    with patch("requests.get", side_effect=requests.exceptions.ConnectionError):
        res = check_health("http://offline-host:8000")
        assert res["is_available"] is False
        assert res["status"] == "offline"
        assert res["model_loaded"] is False
        assert "Connection refused" in res["error_message"]


def test_payload_contains_exactly_19_expected_features(sample_payload_19_features):
    """5. Confirm payload contains exactly the 19 expected features."""
    expected_fields = {
        "gender",
        "SeniorCitizen",
        "Partner",
        "Dependents",
        "tenure",
        "PhoneService",
        "MultipleLines",
        "InternetService",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies",
        "Contract",
        "PaperlessBilling",
        "PaymentMethod",
        "MonthlyCharges",
        "TotalCharges",
    }
    assert set(sample_payload_19_features.keys()) == expected_fields
    assert len(sample_payload_19_features) == 19


def test_predict_churn_success(sample_payload_19_features):
    """6, 9 & 10. Test predict_churn parses response, probability, and risk level."""
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "prediction": 1,
        "churn_label": "Yes",
        "churn_probability": 0.8731,
        "risk_level": "High Risk",
    }

    with patch("requests.post", return_value=mock_resp):
        res = predict_churn(sample_payload_19_features, backend_url="http://dummy-host:8000")
        assert res["success"] is True
        data = res["data"]
        assert data["prediction"] == 1
        assert data["churn_label"] == "Yes"
        assert data["risk_level"] == "High Risk"
        # Probability display conversion test (0.8731 -> 87.31%)
        pct_display = f"{data['churn_probability'] * 100:.2f}%"
        assert pct_display == "87.31%"


def test_predict_churn_validation_error_422(sample_payload_19_features):
    """8. Test 422 validation error handling."""
    mock_resp = MagicMock()
    mock_resp.status_code = 422
    mock_resp.json.return_value = {"detail": "Invalid contract format"}

    with patch("requests.post", return_value=mock_resp):
        res = predict_churn(sample_payload_19_features, backend_url="http://dummy-host:8000")
        assert res["success"] is False
        assert res["status_code"] == 422
        assert "Invalid customer input" in res["error_message"]


def test_streamlit_app_compiles():
    """Verify streamlit_app.py has valid python syntax and can be parsed."""
    app_file = CAPSTONE_ROOT / "frontend" / "streamlit_app.py"
    with open(app_file, "r", encoding="utf-8") as f:
        code = f.read()
    compiled = compile(code, str(app_file), "exec")
    assert compiled is not None
